### ISSUE TITLE
Add geojson

### ISSUE THREAD

**Issue by jobvancreij** [SensingClues/wildcat-api-python#21]
Check if this functionality already exists in python (almost sure it does)

**Comment by ralphdewit** [comment]
Confirmed that we already have this in add_geojson_to_track, it is similar to get_track_as_geojson (from the R-library), in the sense that it does a POST-request to map/all/track/0/features/.

One difference: 
- in get_track_as_geojson, the user has to specify an entityId for a specific (single) track, for which then the geojson-metadata is added.
- in our add_geojson_to_track, we pass as input a dataframe with tracks, and for all of these tracks we then add geojson-metadata. I feel what we now have (the latter approach) is fine; if you only want geojson-metadata for a single track, you could just pass a single track.

One improvement point: pass a list of entityIds to the function, and then merge that with the tracks-dataframe, instead of passing a dataframe as input to the function (as we currently do).

**Comment by ralphdewit** [comment]
Pushed the improvement point mentioned in my previous comment to feature/geojson_track_input.
